permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 莫璇
  email: hadesmo1986@gmail.com
  link: http://hadesmo.com
  github: http://github.com/hadesmo

# 站点信息
title: 莫璇的博客 
description: 这家伙很懒，什么都没留下... 
url: http://hadesmo.org
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: /public/upload/img/site-avatar.png
favicon: /public/upload/img/site-favicon.ico

# google analytics 设置
#ga:
#  id: UA-54767140-1
#  url: hadesmo.org

# disqus 设置
# disqus:
#  shortname: suyan-zh
